### ISSUE TITLE
HAD reverse-mode?

### ISSUE THREAD

**Issue by stumarcus314** [BachiLi/had#3]
Does HAD use reverse-mode AD? Why do you recommend Adept over say Stan Math? This paper about Stan Math (https://arxiv.org/pdf/1509.07164.pdf) indicates that it is similar or even better than Adept at constructing first derivatives.

**Comment by BachiLi** [comment]
Yes, HAD implements [this paper](https://www.ime.unicamp.br/sites/default/files/pesquisa/relatorios/rp-2010-16.pdf) for derivatives computation.  Adept uses a more sophisticated expression template method that is able to utilize more compiler optimizations.  I guess you don't see much difference in the Stan paper because the expressions tested in the paper are fairly simple so not much optimization can be done.  Using modern C++ features like auto also helps a lot in Adept.
