### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by stumarcus314** [BachiLi/had#4]
Have you compared the performance of HAD against CppAD, ADOL-C, Stan Math, autodiff, etc.? When computing the Hessian of f: R^n -> R, is there some threshold N such that HAD is faster than forward-over-forward AD for n>N?

**Comment by BachiLi** [comment]
I didn't do a formal comparison.  I had a very specific application when writing HAD ( https://people.csail.mit.edu/tzumao/h2mc/ ) and HAD was the fastest among all operator overloading approaches (though I end up compiling the derivative code to C since it was even faster).  The "n" I had at that time was around 10~20.
